version: '3.8'

services:
  app_mysql:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PFT
      MYSQL_USER: worker
      MYSQL_PASSWORD: root
    networks:
      - my_network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:80"
    container_name: PFT
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - my_network
    depends_on:
      - app_mysql

  nginx:
    image: nginx
    ports:
      - "8086:80"
    volumes:
      - ./Docker/Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network

networks:
  my_network:
