FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=password123
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=user123

# Copy custom configuration files if needed
# COPY custom.cnf /etc/mysql/conf.d/

# Expose the default MySQL port
EXPOSE 3306

# This command will be executed when the container starts
# CMD ["mysqld"]
